name: Build PHAR on Release

on:
  release:
    types: [created]

jobs:
  build-phar:
    permissions:
      contents: write
    uses: ./.github/workflows/build-phar.yml
    with:
      tag_name: ${{ github.event.release.tag_name }}
