name: Release Please

on:
  push:
    branches:
    - main
  workflow_dispatch:

permissions: {}

jobs:
  release-please:
    uses: opencoreemr/github-workflows-public/.github/workflows/release-please-reusable.yml@0.0.4
    permissions:
      contents: write
      pull-requests: write

  build-phar:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    permissions:
      contents: write
    uses: ./.github/workflows/build-phar.yml
    with:
      tag_name: ${{ needs.release-please.outputs.tag_name }}
